### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by clausmichele** [stac-extensions/processing#22]
[ENVISAT Level-3](http://envisat.esa.int/level3/) is broken, found a copy on the wayback machine from 2017:
https://web.archive.org/web/20170317173521/http://envisat.esa.int/level3/

[Sentinel-2 L3](https://s2gm.sentinel-hub.com/) I am not sure what was this pointing to.

[Sentinel-2 L2A](https://earth.esa.int/web/sentinel/technical-guides/sentinel-2-msi/level-2a-processing)  is broken, this works:
https://sentinel.esa.int/web/sentinel/user-guides/sentinel-2-msi/product-types/level-2a

**Comment by m-mohr** [comment]
> [Sentinel-2 L3](https://s2gm.sentinel-hub.com/) I am not sure what was this pointing to.

It is now at https://s2gm.land.copernicus.eu/

**Comment by m-mohr** [comment]
> [Sentinel-2 L2A](https://earth.esa.int/web/sentinel/technical-guides/sentinel-2-msi/level-2a-processing) is broken, this works: https://sentinel.esa.int/web/sentinel/user-guides/sentinel-2-msi/product-types/level-2a

This is probably meant to be https://sentinel.esa.int/web/sentinel/technical-guides/sentinel-2-msi/level-2a-processing

**Comment by m-mohr** [comment]
> [ENVISAT Level-3](http://envisat.esa.int/level3/) is broken, found a copy on the wayback machine from 2017: https://web.archive.org/web/20170317173521/http://envisat.esa.int/level3/

Alternative might be https://earth.esa.int/eogateway/documents/20142/37627/mkl3_product_handbook_is1r0.pdf
