### ISSUE TITLE
v1.1.0 JSON schema $id attribute is referencing old version

### ISSUE THREAD

**Issue by eddieeda** [stac-extensions/processing#25]
[schema.json](https://github.com/stac-extensions/processing/tree/main/json-schema) `$id` attribute references version `1.0.0` while the URI is for version `1.1.0`.

This issue is presented itself when using  PyStac's [validate_dict](https://pystac.readthedocs.io/en/stable/api/validation.html#pystac.validation.validate_dict) method by first validating a STAC item which specifies the `1.1.0` URI and immediately validating a STAC item that specifies the `1.0.0` URI. The latter fails the JSON schema validation.

**Comment by m-mohr** [comment]
Should be fixed now, thanks for reporting it.
