### ISSUE TITLE
processing baseline and processing timeline

### ISSUE THREAD

**Issue by cbouzina** [stac-extensions/processing#30]
Would it be possible to add two elements : baseline and timeline please ?

The baseline is an identification string regrouping processing conditions to have a coherent dataset in quality.

The timeline is an identification string, usually for Near-Real Time (NRT) or Non-Time Critical (NTC), linked to the auxiliary data quality used by the processing chain.

Note that the baseline and the timeline are complementary indications.

**Comment by m-mohr** [comment]
There's a PR for processing:version (i.e. processing baseline) and processing:datetime (which is different from processing timeline): #32 

Processing timeline should probably be an enum. We'd need to define a vocabulary that is generally used across various products and that's what I'm not sure about so it needs a separate discussion and survey of options used.

**Comment by m-mohr** [comment]
For timeliness see https://github.com/stac-extensions/product
